#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 10 16:37:06 2024

@author: 

v1  zs:  fist version. add lens dust effect.
    need dust texture in dust_mask folder. the dust_mask could be generated by generate_texture_v3.py with mod = 'many_rain_drop'
    
    
"""

import cv2
import numpy as np
import random
import os






def get_texture_random(texture_file_list):
    random_item = random.choice(texture_file_list)
    return random_item
    


def add_lensDustByTxture_hsv(image,dir_texture):
    dir_texture = cv2.resize(dir_texture , (image.shape[1],image.shape[0]) )
    dir_texture = cv2.cvtColor(dir_texture,cv2.COLOR_BGR2GRAY)/255
    image_hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)

    image_dirt_h = image_hsv[:,:,2] * dir_texture 
    image_hsv[:,:,2] = np.minimum(255,np.add(image_dirt_h  , image_hsv[:,:,2]))
    image_rgb = cv2.cvtColor(image_hsv,cv2.COLOR_HSV2BGR)
    
    return image_rgb






texture_mod = 'many_dust_drop'

image = cv2.imread(image_file)
dir_texture = cv2.imread(dir_texture_file) 

texture_file_list = []
texture_file_list = os.listdir(dir_folder)
image_list = []


image_files = 'image'
image_file_list = os.listdir(image_files)

from generate_texture_paper import generate_texture



for item in image_file_list:
    
    image = cv2.imread(os.path.join(image_files,item) , cv2.IMREAD_UNCHANGED  )
    texture_mod = random.choice(texture_mods)
    dir_texture = generate_texture(mod = texture_mod)
    dir_texture = dir_texture[:,:,np.newaxis]



    image_rgb = add_lensDustByTxture_hsv(image,dir_texture)
    image_name = './result_lens_dirt/' + item.split('.')[0] + image_file
    cv2.imwrite(image_name,image_rgb)
    
    

